### ISSUE TITLE
Display dollar amounts for the various clothes

### ISSUE THREAD

**Issue by SGTGunner** [ESX-Org/esx_clotheshop#15]
At the moment, the current clothes don't show a $ amount. So that if a player is trying to work out how much an ensemble would be it is difficult.

Current behavior - no dollar amount is show for each article of clothing.
Expected behavior - show dollar amount on each clothing.

**Comment by TemptressTeelia** [comment]
Everything is $200 no matter the ensemble. Just have to accept it after when you have the desired look

**Comment by SGTGunner** [comment]
Why would everything be at $200, seems that was an easy thing to do as opposed to giving it a price catalog. To make it attractive to buy some clothes ahead of others would be a better model.

**Comment by TemptressTeelia** [comment]
And if you want that then you will need to code it. The amount of work it will take to make your change is crazy! I want to change the way it is and I looked into it I near cried! So much data entry it’s not a joke. But it’s not a bug. 
It’s really an enhancement. And I would be surprised if they do that. 
So yes. That was an easy way. And I don’t blame them.

**Comment by SGTGunner** [comment]
Thanks for the feedback. I don't blame them either. They coded what did at the time. Refactoring is always a fun task. The bigger question is what is the contribution model that the ESX team subscribe to?

That is if I do some refactoring and include a dollar amount and submit a PR would they even look at it?
Not that I am saying they won't, there are a lot of open source communities, that really closed communities and PRs just die on the vine so to speak.

Thanks.

**Comment by TemptressTeelia** [comment]
As long as it is within a certain standard, then they will accept it. In the discord they have the requirements I think in announcements. Not sure. But PRs have been accepted. And still continue to do so.

**Comment by SGTGunner** [comment]
Cool. I will go that route then. Thanks again for your help on this.

Cheers.
