### ISSUE TITLE
Menu issue when running in window mode

### ISSUE THREAD

**Issue by SGTGunner** [ESX-Org/esx_clotheshop#16]
After selecting an item to purchase and then want to get out get presented with the following menu.

![fivem_2018-08-18_13-39-43](https://user-images.githubusercontent.com/13827892/44303087-81e43b80-a2ec-11e8-8ea1-94bcd07e31b7.jpg)

Menu position looks like the image about when running FiveM in Window mode.

**Comment by TemptressTeelia** [comment]
That’s to do with your menu default file. Nothing to do with clothesshop. You need to make it wider int css file

**Comment by SGTGunner** [comment]
Okay. so it is not an adaptive UI then. Is it hardcoded?

**Comment by TemptressTeelia** [comment]
No. You changed the menu default, the default css, it all fits. So you can change it in css, which I said earlier. All menus are customisable.

**Comment by SGTGunner** [comment]
okay, I will look at that. Thanks again.
