### ISSUE TITLE
clothing market bug

### ISSUE THREAD

**Issue by m0iises19** [ESX-Org/esx_clotheshop#35]
I have a problem, when for example I wear police clothes at the police station, if I go through a marker in the clothing store, I take off my police clothes and go back to my normal clothes, why is that? I need help

**Comment by m0iises19** [comment]
some help? @indilo53

**Comment by indilo53** [comment]
Support is over for that esx version, do you guys read the infos we provide ?

In our discord we are linking to other discord so you can still support, or you can also use ExM which is still maintained.
